AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*

Documentation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/CyclomaticComplexity:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/WordArray:
  Enabled: false
