# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production: *redis
development: *redis

test:
  adapter: async
